name: Android - Production

on:
  push:
    branches: [master]

jobs:
  release-android:
    name: Android - Deploy Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Install Fastlane
        run: bundle install

      - name: Install packages
        run: yarn config set network-timeout 100000 & yarn --frozen-lockfile

      - name: Build
        run: fastlane android build

      - name: Distribute
        run: fastlane android distribute_staging

    env:
      APPCENTER_ANDROID_APP_NAME: ${{ secrets.APPCENTER_ANDROID_APP_NAME_PROD }}
      APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
      APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FASTLANE_BUILD_ENVIRONMENT: "production"
